// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RVO.Services.Employees.Infrastructure.Data;

namespace RVO.Services.Employees.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201101012414_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RVO.Services.Employees.Core.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Discontinue")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OfficeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("RVO.Services.Employees.Core.Entities.Employee", b =>
                {
                    b.OwnsOne("RVO.Services.Employees.Core.Entities.OfficeHours", "WeekSchedule", b1 =>
                        {
                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");

                            b1.OwnsOne("RVO.Services.Employees.Core.Entities.DateTimeRange", "FriTimeRange", b2 =>
                                {
                                    b2.Property<Guid>("OfficeHoursEmployeeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("End")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime>("Start")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("OfficeHoursEmployeeId");

                                    b2.ToTable("Employees");

                                    b2.WithOwner()
                                        .HasForeignKey("OfficeHoursEmployeeId");
                                });

                            b1.OwnsOne("RVO.Services.Employees.Core.Entities.DateTimeRange", "MonTimeRange", b2 =>
                                {
                                    b2.Property<Guid>("OfficeHoursEmployeeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("End")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime>("Start")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("OfficeHoursEmployeeId");

                                    b2.ToTable("Employees");

                                    b2.WithOwner()
                                        .HasForeignKey("OfficeHoursEmployeeId");
                                });

                            b1.OwnsOne("RVO.Services.Employees.Core.Entities.DateTimeRange", "SatTimeRange", b2 =>
                                {
                                    b2.Property<Guid>("OfficeHoursEmployeeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("End")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime>("Start")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("OfficeHoursEmployeeId");

                                    b2.ToTable("Employees");

                                    b2.WithOwner()
                                        .HasForeignKey("OfficeHoursEmployeeId");
                                });

                            b1.OwnsOne("RVO.Services.Employees.Core.Entities.DateTimeRange", "SunTimeRange", b2 =>
                                {
                                    b2.Property<Guid>("OfficeHoursEmployeeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("End")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime>("Start")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("OfficeHoursEmployeeId");

                                    b2.ToTable("Employees");

                                    b2.WithOwner()
                                        .HasForeignKey("OfficeHoursEmployeeId");
                                });

                            b1.OwnsOne("RVO.Services.Employees.Core.Entities.DateTimeRange", "ThuTimeRange", b2 =>
                                {
                                    b2.Property<Guid>("OfficeHoursEmployeeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("End")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime>("Start")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("OfficeHoursEmployeeId");

                                    b2.ToTable("Employees");

                                    b2.WithOwner()
                                        .HasForeignKey("OfficeHoursEmployeeId");
                                });

                            b1.OwnsOne("RVO.Services.Employees.Core.Entities.DateTimeRange", "TueTimeRange", b2 =>
                                {
                                    b2.Property<Guid>("OfficeHoursEmployeeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("End")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime>("Start")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("OfficeHoursEmployeeId");

                                    b2.ToTable("Employees");

                                    b2.WithOwner()
                                        .HasForeignKey("OfficeHoursEmployeeId");
                                });

                            b1.OwnsOne("RVO.Services.Employees.Core.Entities.DateTimeRange", "WedTimeRange", b2 =>
                                {
                                    b2.Property<Guid>("OfficeHoursEmployeeId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("End")
                                        .HasColumnType("datetime2");

                                    b2.Property<DateTime>("Start")
                                        .HasColumnType("datetime2");

                                    b2.HasKey("OfficeHoursEmployeeId");

                                    b2.ToTable("Employees");

                                    b2.WithOwner()
                                        .HasForeignKey("OfficeHoursEmployeeId");
                                });
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
